### ISSUE TITLE
HTTPS (Tracking issue)

### ISSUE THREAD

**Issue by Lexicality** [emfcamp/Mk4-Apps#35]
- [ ] Get test running
- [ ] Don't validate by default
- [ ] Make it so you can validate per request
- [ ] Validate the badge store
- [ ] Send SNI in handshake (Currently this breaks cloudflare & cheap hosting)
- [ ] Add Cloudflare root CA by default (On the assumption that most people are behind cloudflare)
- [ ] Document how to add your own certs in an app for validation
